<?xml version="1.0" ?>
<robot name="quattro_4" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="width" value="0.01" /> <!-- all links -->

  <!-- dimension of original lower base   -->
  <xacro:property name="width_12" value="0.01" /> <!-- all links -->
  <xacro:property name="length_12" value="0.127" /> <!-- all links -->
  <xacro:property name="width_m" value="0.02" /> <!-- all links -->
  <xacro:property name="length_m" value="0.18" /> <!-- all links -->

  <xacro:property name="distance_ground" value="2" /> <!-- distance -->
  <xacro:property name="mass_base" value="0.48" /> <!-- base mass-->
  <xacro:property name="mass_low_base" value="0.03" /> <!-- low base mass -->
  <xacro:property name="length_base" value="0.3" /> <!-- base length -->
  <xacro:property name="mass_uleg" value="0.0466" /> <!--upper leg mass-->
  <xacro:property name="length_uleg" value="0.2" /> <!-- upper leg length -->
  <xacro:property name="width_uleg" value="0.05" /> <!-- upper leg width -->
  <xacro:property name="radius_uleg" value="0.01" /> <!-- upper leg width -->

  <xacro:property name="mass_lleg" value="0.04" /> <!-- low leg mass-->
  <xacro:property name="length_lleg" value="0.51" /> <!-- low leg length-->
  <xacro:property name="width_lleg" value="0.002" /> <!-- low leg width -->
  <xacro:property name="mass_con" value="0.0173" /> <!-- connector mass-->

  <xacro:property name="namespace" value="quattro" /> 

  <xacro:macro name="default_inertial2" params="mass length width">
	 <inertia ixx="${1/12*mass*(width*width+length*length)}" ixy="0.0" ixz="0.0"
	  	  iyy="${1/12*mass*(width*width+length*length)}" iyz="0.0"
	 	  izz="${1/12*mass*(width*width+width*width)}"/>
  </xacro:macro>
  <xacro:macro name="default_inertial3" params="mass length width">
	 <inertia ixx="${1/12*mass*(width*width+length*length)}" ixy="0.0" ixz="0.0"
	  	  iyy="${1/12*mass*(width*width+length*length)}" iyz="0.0"
	 	  izz="${1/12*mass*(length*length+length*length)}"/>
  </xacro:macro>
  
 <gazebo>
    <plugin name="my_plugin" filename="libcontact.so"/>
    <plugin filename="libgazebo_ros_control.so" name="gazebo_ros_control">
      <robotNamespace>/delta</robotNamespace>
    <!--  <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType> -->
    </plugin>
    
    <self_collide>true</self_collide>
    <enable_wind>false</enable_wind>
 </gazebo>
 
 <!-- Used for fixing robot to Gazebo 'base_link' 
  <link name="world"/>-->
 
  <link name="world"/>
  
  <joint name="base" type="fixed">
     <parent link="world"/>
     <child link="link_0"/>
     <axis xyz="0 0 0"/>
     <origin xyz="0 0 ${distance_ground}" rpy="0 0 0"/>
  </joint>
  <gazebo reference="world_to_base">
     <physics>
	<ode>
	  <provide_feedback>true</provide_feedback>
	</ode>
     </physics>
  </gazebo>

  <link name="link_0">
    <inertial>
       <origin xyz="-0.0 -0.0 -0.0" rpy="0 0 0"/>
       <mass value="${mass_base}"/>
       <xacro:default_inertial3 mass="${mass_base}" length="${length_base}" width="${width_m}" />
    </inertial>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
	<geometry>
           <box size="${length_base} ${length_base} ${width_m}" />
            <!--<mesh filename="package://delta/meshes/fixed_base2.dae" scale="0.001 0.001 0.001" /> -->
        </geometry>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
          <box size="${length_base}  ${length_base} ${width_m}" />
         <!-- <mesh filename="package://delta/meshes/fixed_base2.dae" scale="0.001 0.001 0.001" /> -->
      </geometry>
    </collision>  
  </link>
  <gazebo reference="link_0">
    <visual>
       <material>
            <script>
              <uri>file://media/materials/scripts/gazebo.material</uri>
              <name>Gazebo/Red</name>
            </script>
       </material>
    </visual>
 </gazebo>

 <gazebo reference="uleg_1">
    <visual>
       <material>
          <script>
             <uri>file://media/materials/scripts/gazebo.material</uri>
             <name>Gazebo/Red</name>
          </script>
       </material>
    </visual>
 </gazebo>
 <gazebo reference="uleg_2">
    <visual>
       <material>
            <script>
              <uri>file://media/materials/scripts/gazebo.material</uri>
              <name>Gazebo/Red</name>
            </script>
       </material>
    </visual>
 </gazebo>
 <gazebo reference="uleg_3">
    <visual>
       <material>
            <script>
              <uri>file://media/materials/scripts/gazebo.material</uri>
              <name>Gazebo/Red</name>
            </script>
       </material>
    </visual>
  </gazebo>
  <gazebo reference="uleg_4">
    <visual>
       <material>
            <script>
              <uri>file://media/materials/scripts/gazebo.material</uri>
              <name>Gazebo/Red</name>
            </script>
       </material>
    </visual>
  </gazebo>
<gazebo reference="low_base">
   <visual>
       <material>
            <script>
              <uri>file://media/materials/scripts/gazebo.material</uri>
              <name>Gazebo/Red</name>
            </script>
       </material>
   </visual>
</gazebo>
<joint name="JOINT_1_ACT" type="revolute">
	<origin xyz="0 -${0.5 * length_base} 0" rpy="0 0 0"/>
	<parent link="link_0"/>
	<child link="uleg_1"/>
        <limit effort="20" velocity="1.0" lower="-0.5" upper="1.1" />
        <axis xyz="1 0 0"/>
</joint>

<joint name="JOINT_2_ACT" type="revolute">
	<origin xyz="${0.5 * length_base} 0 0" rpy="0 0 ${PI/2}"/>
	<parent link="link_0"/>
	<child link="uleg_2"/>
        <limit effort="20" velocity="1.0" lower="-0.5" upper="1.1" />
        <axis xyz="1 0 0"/>
</joint>

<joint name="JOINT_3_ACT" type="revolute">
	<origin xyz="0 ${0.5 * length_base} 0" rpy="0 0 ${PI}"/>
	<parent link="link_0"/>
	<child link="uleg_3"/>
        <limit effort="20" velocity="1.0" lower="-0.5" upper="1.1" />
        <axis xyz="1 0 0"/>
</joint>

<joint name="JOINT_4_ACT" type="revolute">
	<origin xyz="-${0.5 * length_base} 0 0" rpy="0 0 ${3*PI/2}"/>
	<parent link="link_0"/>
	<child link="uleg_4"/>
        <limit effort="20" velocity="1.0" lower="-0.5" upper="1.1" />
        <axis xyz="1 0 0"/>
</joint>

<link name="uleg_1">
    <inertial>
      <origin xyz="0 ${-length_uleg/2+width_uleg/2+0.004}  0 " rpy="${PI/2} 0 0"/>
      <mass value="${mass_uleg}"/>
      <xacro:default_inertial3 mass="${mass_uleg}" width="${length_uleg}" length="${width_uleg}" />
    </inertial>

    <visual>
      <origin xyz="0  ${-length_uleg/2}  0 " rpy="${PI/2} 0 0"/>
	<geometry>
           <!-- <mesh filename="package://delta/meshes/upper_leg.STL" scale="0.001 0.001 0.001" /> -->
           <cylinder length="${length_uleg}" radius="${radius_uleg}" />
        </geometry>
    </visual>
    <collision>
 	<origin xyz="0 ${-length_uleg/2} 0 " rpy="${PI/2} 0 0"/>
	<geometry>
            <!-- <mesh filename="package://delta/meshes/upper_leg.STL" scale="0.001 0.001 0.001" /> -->
            <cylinder length="${length_uleg}" radius="${radius_uleg}" />
        </geometry>
    </collision>  
 </link>

<link name="uleg_2">
    <inertial>
      <origin xyz="0 ${-length_uleg/2+width_uleg/2+0.004}  0 " rpy="${PI/2} 0 0"/>
      <mass value="${mass_uleg}"/>
      <xacro:default_inertial3 mass="${mass_uleg}" width="${length_uleg}" length="${width_uleg}" />
    </inertial>

    <visual>
      <origin xyz="0 ${-length_uleg/2} 0 " rpy="${PI/2} 0 0"/>
	<geometry>
           <!-- <mesh filename="package://delta/meshes/upper_leg.STL" scale="0.001 0.001 0.001" /> -->
           <cylinder length="${length_uleg}" radius="${radius_uleg}" />
        </geometry>
    </visual>
    <collision>
 	<origin xyz="0 ${-length_uleg/2} 0 " rpy="${PI/2} 0 0"/>
	<geometry>
            <!-- <mesh filename="package://delta/meshes/upper_leg.STL" scale="0.001 0.001 0.001" /> -->
            <cylinder length="${length_uleg}" radius="${radius_uleg}" />
        </geometry>
    </collision>  
 </link>
 <link name="uleg_3">
    <inertial>
      <origin xyz="0 ${-length_uleg/2+width_uleg/2+0.004}  0 " rpy="${PI/2} 0 0"/>
      <mass value="${mass_uleg}"/>
 	<xacro:default_inertial3 mass="${mass_uleg}" width="${length_uleg}" length="${width_uleg}" />
    </inertial>

    <visual>
      <origin xyz="0 ${-length_uleg/2} 0 " rpy="${PI/2} 0 0"/>
	<geometry>
            <!-- <mesh filename="package://delta/meshes/upper_leg.STL" scale="0.001 0.001 0.001" /> -->
            <cylinder length="${length_uleg}" radius="${radius_uleg}" />
        </geometry>
    </visual>
    <collision>     
 	<origin xyz="0 ${-length_uleg/2} 0 " rpy="${PI/2} 0 0"/>
	<geometry>
            <!-- <mesh filename="package://delta/meshes/upper_leg.STL" scale="0.001 0.001 0.001" /> -->
            <cylinder length="${length_uleg}" radius="${radius_uleg}" />
        </geometry>
    </collision>  
 </link>

 <link name="uleg_4">
    <inertial>
      <origin xyz="0 ${-length_uleg/2+width_uleg/2+0.004}  0 " rpy="${PI/2} 0 0"/>
      <mass value="${mass_uleg}"/>
 	<xacro:default_inertial3 mass="${mass_uleg}" width="${length_uleg}" length="${width_uleg}" />
    </inertial>

    <visual>
      <origin xyz="0 ${-length_uleg/2} 0 " rpy="${PI/2} 0 0"/>
	<geometry>
            <!-- <mesh filename="package://delta/meshes/upper_leg.STL" scale="0.001 0.001 0.001" /> -->
            <cylinder length="${length_uleg}" radius="${radius_uleg}" />
        </geometry>
    </visual>
    <collision>     
 	<origin xyz="0 ${-length_uleg/2} 0 " rpy="${PI/2} 0 0"/>
	<geometry>
            <!-- <mesh filename="package://delta/meshes/upper_leg.STL" scale="0.001 0.001 0.001" /> -->
            <cylinder length="${length_uleg}" radius="${radius_uleg}" />
        </geometry>
    </collision>  
 </link>



<joint name="uleg1_con" type="continuous">
	 <origin xyz="0 -0.2 0" rpy="${PI/2-1.0358} 0 0"/>
	 <parent link="uleg_1"/>
	 <child link="con1"/>
         <axis xyz="1 0 0"/>
</joint>



<link name="con1">
    <inertial>
      <origin xyz="0.00 0 0 " rpy="0 ${PI/2} 0"/>
      <mass value="${mass_con}"/>
 	<xacro:default_inertial2 mass="${mass_con}" width="0.002" length="0.05" />
    </inertial>

    <visual>
      <origin xyz="0.00 0 0 " rpy="0 ${PI/2} 0"/>
      <geometry>
          <cylinder length="0.05" radius="0.002" />
      </geometry> 
    </visual>
    <collision>
      <origin xyz="0.000 0 0 " rpy="0 ${PI/2} 0 "/>
      <geometry>
          <cylinder length="0.05" radius="0.002" />
      </geometry>   
    </collision>  
 </link>

 <joint name="con_lleg_1" type="continuous">
	<origin xyz="-0.025 0 0" rpy="0 0 0"/>
	 <parent link="con1"/>
	 <child link="lleg_1"/>
        <axis xyz="0 1 0"/>
 </joint>


<link name="lleg_1">
    <inertial>
      <origin xyz="0 0 ${-length_lleg/2} " rpy="0 0 0"/>
      <mass value="${mass_lleg}"/>
 	<xacro:default_inertial3 mass="${mass_lleg}" width="${length_lleg}" length="${width_lleg}" />
    </inertial>

    <visual>
      <origin xyz=" 0 0 ${-length_lleg/2} " rpy="0 0 0"/>
      <geometry>
          <cylinder length="${length_lleg}" radius="${width_lleg}" />
      </geometry> 
    </visual>
    <collision>
 	<origin xyz="0 0 ${-length_lleg/2} " rpy="0 0 0 "/>
      <geometry>
          <cylinder length="${length_lleg}" radius="${width_lleg}" />
      </geometry>   
    </collision>  
 </link>

<joint name="con2_lleg_1" type="continuous">
	<origin xyz="0.025 0 0" rpy="0 0 0"/>
	 <parent link="con1"/>
	 <child link="lleg_12"/>
	<mimic joint="con_lleg_1"/>
        <axis xyz="0 1 0"/>
</joint>


<link name="lleg_12">
      <inertial>
      <origin xyz="0 0 ${-length_lleg/2} " rpy="0 0 0"/>
      <mass value="${mass_lleg}"/>
 	<xacro:default_inertial3 mass="${mass_lleg}" width="${length_lleg}" length="${width_lleg}" />
    </inertial>

    <visual>
      <origin xyz=" 0 0 ${-length_lleg/2} " rpy="0 0 0"/>
      <geometry>
          <cylinder length="${length_lleg}" radius="${width_lleg}" />
      </geometry> 
    </visual>
    <collision>
 	<origin xyz="0 0 ${-length_lleg/2} " rpy="0 0 0 "/>
      <geometry>
          <cylinder length="${length_lleg}" radius="${width_lleg}" />
      </geometry>   
    </collision>  
 </link>


<joint name="uleg2_con" type="continuous">
	<origin xyz="0 -0.2 0" rpy="${PI/2-1.0358} 0 0"/>
	 <parent link="uleg_2"/>
	 <child link="con2"/>
        <axis xyz="1 0 0"/>
</joint>



<link name="con2">
    <inertial>
      <origin xyz="0.00 0 0 " rpy="0 ${PI/2} 0"/>
      <mass value="${mass_con}"/>
      <xacro:default_inertial2 mass="${mass_con}" width="0.002" length="0.05" />
    </inertial>

    <visual>
      <origin xyz="0.00 0 0 " rpy="0 ${PI/2} 0"/>
      <geometry>
          <cylinder length="0.05" radius="0.002" />
      </geometry> 
    </visual>
    <collision>
      <origin xyz="0.00 0 0 " rpy="0 ${PI/2} 0 "/>
      <geometry>
          <cylinder length="0.05" radius="0.002" />
      </geometry>   
    </collision>  
 </link>

<joint name="con_lleg_2" type="continuous">
	<origin xyz="-0.025 0 0" rpy="0 0 0"/>
	 <parent link="con2"/>
	 <child link="lleg_2"/>
        <axis xyz="0 1 0"/>
</joint>


<link name="lleg_2">
      <inertial>
      <origin xyz="0 0 ${-length_lleg/2} " rpy="0 0 0"/>
      <mass value="${mass_lleg}"/>
 	<xacro:default_inertial3 mass="${mass_lleg}" width="${length_lleg}" length="${width_lleg}" />
    </inertial>

    <visual>
      <origin xyz=" 0 0 ${-length_lleg/2} " rpy="0 0 0"/>
      <geometry>
          <cylinder length="${length_lleg}" radius="${width_lleg}" />
      </geometry> 
    </visual>
    <collision>
 	<origin xyz="0 0 ${-length_lleg/2} " rpy="0 0 0 "/>
      <geometry>
          <cylinder length="${length_lleg}" radius="${width_lleg}" />
      </geometry>   
    </collision>  
 </link>

<joint name="con2_lleg_2" type="continuous">
	<origin xyz="0.025 0 0" rpy="0 0 0"/>
	 <parent link="con2"/>
	 <child link="lleg_22"/>
         <mimic joint="con_lleg_2"/>
        <axis xyz="0 1 0"/>
</joint>


<link name="lleg_22">
      <inertial>
      <origin xyz="0 0 ${-length_lleg/2} " rpy="0 0 0"/>
      <mass value="${mass_lleg}"/>
 	<xacro:default_inertial3 mass="${mass_lleg}" width="${length_lleg}" length="${width_lleg}" />
    </inertial>

    <visual>
      <origin xyz=" 0 0 ${-length_lleg/2} " rpy="0 0 0"/>
      <geometry>
          <cylinder length="${length_lleg}" radius="${width_lleg}" />
      </geometry> 
    </visual>
    <collision>
 	<origin xyz="0 0 ${-length_lleg/2} " rpy="0 0 0 "/>
      <geometry>
          <cylinder length="${length_lleg}" radius="${width_lleg}" />
      </geometry>   
    </collision>  
 </link>



<joint name="uleg3_con" type="continuous">
	<origin xyz="0 -0.2 0" rpy="${PI/2-1.0358} 0 0"/>
	 <parent link="uleg_3"/>
	 <child link="con3"/>
        <axis xyz="1 0 0"/>
</joint>



<link name="con3">
    <inertial>
      <origin xyz="0.00 0 0 " rpy="0 ${PI/2} 0"/>
      <mass value="${mass_con}"/>
      <xacro:default_inertial2 mass="${mass_con}" width="0.002" length="0.05" />
    </inertial>

    <visual>
      <origin xyz="0.00 0 0 " rpy="0 ${PI/2} 0"/>
      <geometry>
          <cylinder length="0.05" radius="0.002" />
      </geometry> 
    </visual>
    <collision>
      <origin xyz="0.00 0 0 " rpy="0 ${PI/2} 0 "/>
      <geometry>
          <cylinder length="0.05" radius="0.002" />
      </geometry>   
    </collision>  
 </link>

<joint name="con_lleg_3" type="continuous">
	<origin xyz="-0.025 0 0" rpy="0 0 0"/>
	 <parent link="con3"/>
	 <child link="lleg_3"/>
        <axis xyz="0 1 0"/>
</joint>


<link name="lleg_3">
      <inertial>
      <origin xyz="0 0 ${-length_lleg/2} " rpy="0 0 0"/>
      <mass value="${mass_lleg}"/>
 	<xacro:default_inertial3 mass="${mass_lleg}" width="${length_lleg}" length="${width_lleg}" />
    </inertial>

    <visual>
      <origin xyz=" 0 0 ${-length_lleg/2} " rpy="0 0 0"/>
      <geometry>
          <cylinder length="${length_lleg}" radius="0.002" />
      </geometry> 
    </visual>
    <collision>
 	<origin xyz="0 0 ${-length_lleg/2} " rpy="0 0 0 "/>
      <geometry>
          <cylinder length="${length_lleg}" radius="0.002" />
      </geometry>   
    </collision>  
 </link>

<joint name="con2_lleg_3" type="continuous">
	<origin xyz="0.025 0 0" rpy="0 0 0"/>
	 <parent link="con3"/>
	 <child link="lleg_32"/>
         <mimic joint="con_lleg_3"/>
        <axis xyz="0 1 0"/>
</joint>


<link name="lleg_32">
      <inertial>
      <origin xyz="0 0 ${-length_lleg/2} " rpy="0 0 0"/>
      <mass value="${mass_lleg}"/>
 	<xacro:default_inertial3 mass="${mass_lleg}" width="${length_lleg}" length="${width_lleg}" />
    </inertial>

    <visual>
      <origin xyz=" 0 0 ${-length_lleg/2} " rpy="0 0 0"/>
      <geometry>
          <cylinder length="${length_lleg}" radius="${width_lleg}" />
      </geometry> 
    </visual>
    <collision>
 	<origin xyz="0 0 ${-length_lleg/2} " rpy="0 0 0 "/>
      <geometry>
          <cylinder length="${length_lleg}" radius="${width_lleg}" />
      </geometry>   
    </collision>  
 </link>


<joint name="uleg4_con" type="continuous">
	<origin xyz="0 -0.2 0" rpy="${PI/2-1.0358} 0 0"/>
	 <parent link="uleg_4"/>
	 <child link="con4"/>
        <axis xyz="1 0 0"/>
</joint>



<link name="con4">
    <inertial>
      <origin xyz="0.00 0 0 " rpy="0 ${PI/2} 0"/>
      <mass value="${mass_con}"/>
      <xacro:default_inertial2 mass="${mass_con}" width="0.002" length="0.05" />
    </inertial>

    <visual>
      <origin xyz="0.00 0 0 " rpy="0 ${PI/2} 0"/>
      <geometry>
          <cylinder length="0.05" radius="0.002" />
      </geometry> 
    </visual>
    <collision>
      <origin xyz="0.00 0 0 " rpy="0 ${PI/2} 0 "/>
      <geometry>
          <cylinder length="0.05" radius="0.002" />
      </geometry>   
    </collision>  
 </link>

<joint name="con_lleg_4" type="continuous">
	<origin xyz="-0.025 0 0" rpy="0 0 0"/>
	 <parent link="con4"/>
	 <child link="lleg_4"/>
        <axis xyz="0 1 0"/>
</joint>


<link name="lleg_4">
      <inertial>
      <origin xyz="0 0 ${-length_lleg/2} " rpy="0 0 0"/>
      <mass value="${mass_lleg}"/>
 	<xacro:default_inertial3 mass="${mass_lleg}" width="${length_lleg}" length="${width_lleg}" />
    </inertial>

    <visual>
      <origin xyz=" 0 0 ${-length_lleg/2} " rpy="0 0 0"/>
      <geometry>
          <cylinder length="${length_lleg}" radius="0.002" />
      </geometry> 
    </visual>
    <collision>
 	<origin xyz="0 0 ${-length_lleg/2} " rpy="0 0 0 "/>
      <geometry>
          <cylinder length="${length_lleg}" radius="0.002" />
      </geometry>   
    </collision>  
 </link>

<joint name="con2_lleg_4" type="continuous">
	<origin xyz="0.025 0 0" rpy="0 0 0"/>
	 <parent link="con4"/>
	 <child link="lleg_42"/>
         <mimic joint="con_lleg_4"/>
        <axis xyz="0 1 0"/>
</joint>


<link name="lleg_42">
      <inertial>
      <origin xyz="0 0 ${-length_lleg/2} " rpy="0 0 0"/>
      <mass value="${mass_lleg}"/>
 	<xacro:default_inertial3 mass="${mass_lleg}" width="${length_lleg}" length="${width_lleg}" />
    </inertial>

    <visual>
      <origin xyz=" 0 0 ${-length_lleg/2} " rpy="0 0 0"/>
      <geometry>
          <cylinder length="${length_lleg}" radius="${width_lleg}" />
      </geometry> 
    </visual>
    <collision>
 	<origin xyz="0 0 ${-length_lleg/2} " rpy="0 0 0 "/>
      <geometry>
          <cylinder length="${length_lleg}" radius="${width_lleg}" />
      </geometry>   
    </collision>  
 </link>


<joint name="con43_lleg_4" type="continuous">
	<origin xyz="0 0 -0.51" rpy="0 0 0"/>
	 <parent link="lleg_42"/>
	 <child link="con43"/>
        <axis xyz="0 1 0"/>
</joint>


<link name="con43">
      <inertial>
      <origin xyz="-0.025  0 0 " rpy="0 ${PI/2} 0"/>
      <mass value="${mass_con}"/>
 	<xacro:default_inertial2 mass="${mass_con}" width="0.002" length="0.05" />
    </inertial>

    <visual>
      <origin xyz="-0.025 0 0  " rpy="0 ${PI/2} 0"/>
      <geometry>
          <cylinder length="0.05" radius="0.002" />
      </geometry> 
    </visual>
    <collision>
 	<origin xyz="-0.025 0  0 " rpy="0 ${PI/2} 0 "/>
      <geometry>
          <cylinder length="0.05" radius="0.002" />
      </geometry>   
    </collision>  
 </link>



<joint name="con33_lleg_3" type="continuous">
	<origin xyz="0 0 -0.51" rpy="0 0 0"/>
	 <parent link="lleg_32"/>
	 <child link="con33"/>
        <axis xyz="0 1 0"/>
</joint>


<link name="con33">
      <inertial>
      <origin xyz="-0.025  0 0 " rpy="0 ${PI/2} 0"/>
      <mass value="${mass_con}"/>
 	<xacro:default_inertial2 mass="${mass_con}" width="0.002" length="0.05" />
    </inertial>

    <visual>
      <origin xyz="-0.025 0 0  " rpy="0 ${PI/2} 0"/>
      <geometry>
          <cylinder length="0.05" radius="0.002" />
      </geometry> 
    </visual>
    <collision>
 	<origin xyz="-0.025 0  0 " rpy="0 ${PI/2} 0 "/>
      <geometry>
          <cylinder length="0.05" radius="0.002" />
      </geometry>   
    </collision>  
 </link>




<joint name="con23_lleg_2" type="continuous">
	<origin xyz="0 0 -0.51" rpy="0 0 0"/>
	 <parent link="lleg_22"/>
	 <child link="con23"/>
        <axis xyz="0 1 0"/>
</joint>


<link name="con23">
      <inertial>
      <origin xyz="-0.025  0 0 " rpy="0 ${PI/2} 0"/>
      <mass value="${mass_con}"/>
 	<xacro:default_inertial2 mass="${mass_con}" width="0.002" length="0.05" />
    </inertial>

    <visual>
      <origin xyz="-0.025 0 0  " rpy="0 ${PI/2} 0"/>
      <geometry>
          <cylinder length="0.05" radius="0.002" />
      </geometry> 
    </visual>
    <collision>
 	<origin xyz="-0.025 0  0 " rpy="0 ${PI/2} 0 "/>
      <geometry>
          <cylinder length="0.05" radius="0.002" />
      </geometry>   
    </collision>  
 </link>



<joint name="con13_lleg_1" type="continuous">
	<origin xyz="0 0 -0.51" rpy="0 0 0"/>
	<parent link="lleg_12"/>
	<child link="con13"/>
        <axis xyz="0 1 0"/>
</joint>


<link name="con13">
      <inertial>
      <origin xyz="-0.025  0 0 " rpy="0 ${PI/2} 0"/>
      <mass value="${mass_con}"/>
 	<xacro:default_inertial2 mass="${mass_con}" width="0.002" length="0.05" />
    </inertial>

    <visual>
      <origin xyz="-0.025 0 0  " rpy="0 ${PI/2} 0"/>
      <geometry>
          <cylinder length="0.05" radius="0.002" />
      </geometry> 
    </visual>
    <collision>
 	<origin xyz="-0.025 0  0 " rpy="0 ${PI/2} 0 "/>
      <geometry>
          <cylinder length="0.05" radius="0.002" />
      </geometry>   
    </collision>  
 </link>




<joint name='lleg1_base_1' type='continuous'>
	<origin xyz=" 0 0 0" rpy="-0.5350 0 0"/>
	 <parent link="con13"/>
	 <child link="low_base_1"/>
        <axis xyz="1 0 0"/>
</joint>



<link name='low_base_1'>
  <inertial>
     <origin xyz="0.02 0.045 0" rpy="0 ${PI/2} ${PI/4}"/>
     <mass value="${mass_con}"/>
     <xacro:default_inertial2 mass="${mass_con}" width="${width_12}" length="${length_12}" />
  </inertial>
  <visual name='low_base_visual'>
        <origin xyz="0.02 0.045 0" rpy="0 ${PI/2} ${PI/4}"/>
	<geometry>
            <cylinder length="${length_12}" radius="${width_12}" />
            <!--<box size="${length_m} ${length_m} ${width_m}" /> -->
            <!--<mesh filename="package://delta/meshes/Platform.STL" scale="0.001 0.001 0.001" /> -->
        </geometry>
  </visual>
</link>


<joint name='base_1_2' type='continuous'>
	<origin xyz="${length_12/1.414} ${length_12/1.414} 0" rpy="0 0 0"/>
	 <parent link="low_base_1"/>
	 <child link="low_base_2"/>
        <axis xyz="0 0 1"/>
</joint>



<link name='low_base_2'>
  <inertial>
     <origin xyz="-0.065 0.045 0" rpy="0 ${PI/2} ${3*PI/4}"/>
     <mass value="${mass_con}"/>
     <xacro:default_inertial2 mass="${mass_con}" width="${width_12}" length="${length_12}" />
  </inertial>
  <visual name='low_base_visual'>
        <origin xyz="-0.065 0.045 0" rpy="0 ${PI/2} ${3*PI/4}"/>
	<geometry>
            <cylinder length="${length_12}" radius="${width_12}" />
            <!--<box size="${length_m} ${length_m} ${width_m}" /> -->
            <!--<mesh filename="package://delta/meshes/Platform.STL" scale="0.001 0.001 0.001" /> -->
        </geometry>
  </visual>
</link>


<joint name='lleg3_base_3' type='continuous'>
	<origin xyz=" 0 0 0" rpy="-0.5350 0 0"/>
	 <parent link="con33"/>
	 <child link="low_base_3"/>
        <axis xyz="1 0 0"/>
</joint>



<link name='low_base_3'>
  <inertial>
     <origin xyz="0.02 0.045 0" rpy="0 ${PI/2} ${PI/4}"/>
     <mass value="${mass_con}"/>
     <xacro:default_inertial2 mass="${mass_con}" width="${width_12}" length="${length_12}" />
  </inertial>
  <visual name='low_base_visual'>
        <origin xyz="0.02 0.045 0" rpy="0 ${PI/2} ${PI/4}"/>
	<geometry>
            <cylinder length="${length_12}" radius="${width_12}" />
            <!--<box size="${length_m} ${length_m} ${width_m}" /> -->
            <!--<mesh filename="package://delta/meshes/Platform.STL" scale="0.001 0.001 0.001" /> -->
        </geometry>
  </visual>
</link>

<joint name='base_3_4' type='continuous'>
	<origin xyz="${length_12/1.414} ${length_12/1.414} 0" rpy="0 0 0"/>
	 <parent link="low_base_3"/>
	 <child link="low_base_4"/>
        <axis xyz="0 0 1"/>
</joint>



<link name='low_base_4'>
  <inertial>
     <origin xyz="-0.065 0.045 0" rpy="0 ${PI/2} ${3*PI/4}"/>
     <mass value="${mass_con}"/>
     <xacro:default_inertial2 mass="${mass_con}" width="${width_12}" length="${length_12}" />
  </inertial>
  <visual name='low_base_visual'>
        <origin xyz="-0.065 0.045 0" rpy="0 ${PI/2} ${3*PI/4}"/>
	<geometry>
            <cylinder length="${length_12}" radius="${width_12}" />
            <!--<box size="${length_m} ${length_m} ${width_m}" /> -->
            <!--<mesh filename="package://delta/meshes/Platform.STL" scale="0.001 0.001 0.001" /> -->
        </geometry>
  </visual>
</link>

<gazebo>
   <joint name='lleg2_base_1' type='revolute'>
      <child>con23</child>
      <parent>low_base_1</parent>
      <pose> 0 0 0 0 0 0 </pose>
      <axis>
        <xyz>1 0 0</xyz>
        <limit>
          <lower>-100</lower>
          <upper>100</upper>
        </limit>
         <dynamics>
          <spring_reference>0</spring_reference>
          <spring_stiffness>0</spring_stiffness>
	  <damping>0.000000</damping>
          <friction>0.00030000</friction>
        </dynamics>
        <use_parent_model_frame>0</use_parent_model_frame>
      </axis>
   </joint>

    <joint name='lleg4_base_3' type='revolute'>
      <child>con43</child>
      <parent>low_base_3</parent>
      <pose> 0 0 0 0 0 0 </pose>
      <axis>
        <xyz>1 0 0</xyz>
        <limit>
          <lower>-100</lower>
          <upper>100</upper>
        </limit>
         <dynamics>
          <spring_reference>0</spring_reference>
          <spring_stiffness>0</spring_stiffness>
	  <damping>0.000000</damping>
          <friction>0.00030000</friction>
        </dynamics>
        <use_parent_model_frame>0</use_parent_model_frame>
      </axis>

    </joint>


    <joint name='con13_lleg_12' type='revolute'>
      <child>con13</child>
      <parent>lleg_1</parent>
      <pose> -0.05 0 0 0 0 0 </pose>
      <axis>
        <xyz>0 1 0</xyz>
        <limit>
          <lower>-100</lower>
          <upper>100</upper>
        </limit>
         <dynamics>
          <spring_reference>0</spring_reference>
          <spring_stiffness>0</spring_stiffness>
	  <damping>0.000000</damping>
          <friction>0.00030000</friction>
        </dynamics>
        <use_parent_model_frame>0</use_parent_model_frame>
      </axis>

    </joint>

    <joint name='con23_lleg_22' type='revolute'>
      <child>con23</child>
      <parent>lleg_2</parent>
      <pose> -0.05 0 0 0 0 0 </pose>
      <axis>
        <xyz>0 1 0</xyz>
        <limit>
          <lower>-100</lower>
          <upper>100</upper>
        </limit>
         <dynamics>
          <spring_reference>0</spring_reference>
          <spring_stiffness>0</spring_stiffness>
	  <damping>0.000000</damping>
          <friction>0.00030000</friction>
        </dynamics>
        <use_parent_model_frame>0</use_parent_model_frame>
      </axis>

    </joint>
    <joint name='con33_lleg_32' type='revolute'>
      <child>con33</child>
      <parent>lleg_3</parent>
      <pose> -0.05 0 0 0 0 0 </pose>
      <axis>
        <xyz>0 1 0</xyz>
        <limit>
          <lower>-100</lower>
          <upper>100</upper>
        </limit>
         <dynamics>
          <spring_reference>0</spring_reference>
          <spring_stiffness>0</spring_stiffness>
	  <damping>0.000000</damping>
          <friction>0.00030000</friction>
        </dynamics>
        <use_parent_model_frame>0</use_parent_model_frame>
      </axis>

    </joint>
    <joint name='con43_lleg_42' type='revolute'>
      <child>con43</child>
      <parent>lleg_4</parent>
      <pose> -0.05 0 0 0 0 0 </pose>
      <axis>
        <xyz>0 1 0</xyz>
        <limit>
          <lower>-100</lower>
          <upper>100</upper>
        </limit>
         <dynamics>
          <spring_reference>0</spring_reference>
          <spring_stiffness>0</spring_stiffness>
	  <damping>0.000000</damping>
          <friction>0.00030000</friction>
        </dynamics>
        <use_parent_model_frame>0</use_parent_model_frame>
      </axis>
    </joint> 
    
    <joint name='base_2_3' type='revolute'>
      <child>lower_base_3</child>
      <parent>lower_base_2</parent>
      <pose>  -0.09 0.09 0 0 0 0</pose>
      <axis>
        <xyz>0 0 1</xyz>
        <limit>
          <lower>-100</lower>
          <upper>100</upper>
        </limit>
         <dynamics>
          <spring_reference>0</spring_reference>
          <spring_stiffness>0</spring_stiffness>
	  <damping>0.000000</damping>
          <friction>0.00030000</friction>
        </dynamics>
        <use_parent_model_frame>0</use_parent_model_frame>
      </axis>
    </joint> 
    
    <joint name='base_4_1' type='revolute'>
      <child>lower_base_1</child>
      <parent>lower_base_4</parent>
      <pose>  -0.09 0.09 0 0 0 0</pose>
      <axis>
        <xyz>0 0 1</xyz>
        <limit>
          <lower>-100</lower>
          <upper>100</upper>
        </limit>
         <dynamics>
          <spring_reference>0</spring_reference>
          <spring_stiffness>0</spring_stiffness>
	  <damping>0.000000</damping>
          <friction>0.00030000</friction>
        </dynamics>
        <use_parent_model_frame>0</use_parent_model_frame>
      </axis>
    </joint> 
    
</gazebo>

  <transmission name="tran1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="JOINT_1_ACT">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="JOINT_2_ACT">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran3">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="JOINT_3_ACT">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor3">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran4">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="JOINT_4_ACT">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor4">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
 
<!--
<gazebo>
    <plugin name="gazebo_ros_f3d" filename="libgazebo_ros_f3d.so">
        <alwaysOn>true</alwaysOn>
        <updateRate>100.0</updateRate>
        <bodyName>/delta/world</bodyName>
        <topicName>world/f3d</topicName>
        <frameName>/delta/world</frameName>
        
        <bodyName>${namespace}/base_link</bodyName>
        <topicName>base_link/f3d</topicName>
        <frameName>${namespace}/base_link</frameName>
         
    </plugin>

</gazebo>
-->
</robot>
