delta:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: JOINT_1_ACT
    pid: {p: 500.0, i: 5, d: 10}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: JOINT_2_ACT
    pid: {p: 500.0, i: 5, d: 10}
  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: JOINT_3_ACT
    pid: {p: 500.0, i: 5, d: 10}
  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: JOINT_4_ACT
    pid: {p: 500.0, i: 5, d: 10}
