<?xml version="1.0"?>
<package format="3">
    <name>quattro_bot</name>
    <version>1.0.0</version>
    <description>The quattro robot simulation package</description>

    <maintainer email="leon@robnux.net">Leon Liu</maintainer>

    <license>MIT</license>

    <buildtool_depend>ament_cmake</buildtool_depend>
    
    <build_depend>sensor_msgs</build_depend>
    <build_depend>std_msgs</build_depend>
    <build_depend>simple_motion_logger</build_depend>
    <build_depend>robnux_kinematics_map</build_depend>
    <build_depend>robnux_kdl_common</build_depend>
    <build_depend>robnux_trajectory</build_depend>
    
    <exec_depend>sensor_msgs</exec_depend>
    <exec_depend>std_msgs</exec_depend>
    <exec_depend>simple_motion_logger</exec_depend>
    <exec_depend>robnux_kinematics_map</exec_depend>
    <exec_depend>robnux_kdl_common</exec_depend>
    <exec_depend>robnux_trajectory</exec_depend>
    
    <export>
    </export>
</package>
    
