<?xml version="1.0"?>
<package format="3">
    <name>scurve_lib</name>
    <version>1.0.0</version>
    <description>7-seg smooth speed profile (continuous acceleration) for trajectory planning of robot arm</description>

    <maintainer email="leon@robnux.net">Leon Liu, ROBNUX LLC</maintainer>

    <license>MIT</license>

    <buildtool_depend>ament_cmake</buildtool_depend>
    
    <build_depend>simple_motion_logger</build_depend>
    <exec_depend>simple_motion_logger</exec_depend>
    
    <export>
    </export>
</package>
