<?xml version="1.0"?>
<package format="3">
    <name>simple_motion_logger</name>
    <version>1.0.0</version>
    <description>A package for doing simple logging of robot motion related data</description>

    <maintainer email="leon@robnux.net">Leon Liu, ROBNUX LLC</maintainer>

    <license>MIT</license>

    <buildtool_depend>ament_cmake</buildtool_depend>
    
    <export>
    </export>
</package>
    
